# Generated by Django 5.2.2 on 2025-06-07 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Due_date', models.DateField(default=datetime.date.today)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
    ]
