# Generated by Django 5.2.2 on 2025-06-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='Status',
            field=models.CharField(default='incomplete'),
        ),
    ]
