# Generated by Django 5.2.2 on 2025-06-07 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_taskmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='Due_date',
            field=models.CharField(default=datetime.date.today),
        ),
    ]
